
USE SchoolManagement;
GO

-- Replace the hash with a bcrypt hash generated by the backend for your production password.
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = 'admin@aurora.edu')
BEGIN
  INSERT INTO dbo.Users (Email, PasswordHash, Role)
  VALUES ('admin@aurora.edu', '$2a$12$replace_with_real_bcrypt_hash', 'admin');
END;
GO
